version: "3"

services:
  backend:
    build: .
    container_name: backend-container
    ports:
      - 4000:4000
    env_file:
      - .env
  nginx:
      image: nginx
      container_name: nginx-container
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf